apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuer.yaml
patches:
  - path: cluster-issuer.yaml
    target:
      kind: ClusterIssuer
      name: letsencrypt
