---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: santa
  namespace: flux-system
spec:
  runnerPodTemplate:
    spec:
      env:
        - name: TF_VAR_environment
          value: prod
