---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: vote
  namespace: flux-system
spec:
  vars:
    - name: environment
      value: production
    - name: container_image
      value: mcr.microsoft.com/azuredocs/azure-vote-front:v1
    - name: ingress_rule_host
      value: vote.20.123.4.196.nip.io
  runnerPodTemplate:
    spec:
      env:
        - name: ARM_TENANT_ID
          value: 7ddc4c97-c5a0-4a29-ac83-59be0f280518
        - name: ARM_SUBSCRIPTION_ID
          value: ae9db8ac-2682-4a98-ad36-7d13b2bd5a24
        - name: ARM_CLIENT_ID
          value: 3b633b6d-43bd-4568-b536-e30bb50284fb
        - name: ARM_USE_OIDC
          value: "true"
        - name: ARM_OIDC_TOKEN_FILE_PATH
          value: /var/run/secrets/azure/tokens/azure-identity-token
