apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/santa
  - ../base/vote
patches:
  - path: santa.yaml
    target:
      kind: Terraform
      name: santa
  - path: vote.yaml
    target:
      kind: Terraform
      name: vote
