---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: santa
  namespace: flux-system
spec:
  path: ./apps/base/santa/terraform
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: "true"
  sourceRef:
    kind: GitRepository
    name: flux-system
  runnerPodTemplate:
    metadata:
      labels:
        azure.workload.identity/use: "true"
  tfstate:
    forceUnlock: "yes"
    lockIdentifier: f0b67037-114f-f5f1-cac1-a67575288ccf
