---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: santa
  namespace: flux-system
spec:
  path: ./apps/base/santa/terraform
  interval: 1m
  approvePlan: auto
  backendConfig:
    customConfiguration: |
      backend "azurerm" {
        subscription_id      = "ae9db8ac-2682-4a98-ad36-7d13b2bd5a24"
        storage_account_name = "stjingle040158"
        resource_group_name  = "rg-tfstate-jingle-neu"
        container_name       = "tfstate"
        key                  = "santa.production.northeurope.tfstate"
      }
  sourceRef:
    kind: GitRepository
    name: flux-system
  runnerPodTemplate:
    metadata:
      labels:
        azure.workload.identity/use: "true"
