---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  values:
    runner:
      serviceAccount:
        annotations:
          azure.workload.identity/client-id: 6020266e-55e4-47ab-933e-abb02bf086ab
