---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  values:
    runner:
      serviceAccount:
        annotations:
          azure.workload.identity/client-id: 3b633b6d-43bd-4568-b536-e30bb50284fb
