---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: hello
  namespace: flux-system
spec:
  path: ./apps/hello/terraform
  interval: 1m
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: flux-system
  runnerPodTemplate:
    metadata:
      labels:
        azure.workload.identity/use: "true"
